// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package instance

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer-plugin-nebius/builder/common"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName      *string                          `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType    *string                          `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion    *string                          `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug          *bool                            `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce          *bool                            `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError        *string                          `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars       map[string]string                `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars  []string                         `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	ParentID             *string                          `mapstructure:"parent_id" cty:"parent_id" hcl:"parent_id"`
	ServiceAccountConfig *common.FlatServiceAccountConfig `mapstructure:"service_account" cty:"service_account" hcl:"service_account"`
	DiskConfig           *common.FlatDiskConfig           `mapstructure:"disk" cty:"disk" hcl:"disk"`
	BaseImageConfig      *common.FlatBaseImageConfig      `mapstructure:"base_image" cty:"base_image" hcl:"base_image"`
	NetworkConfig        *common.FlatNetworkConfig        `mapstructure:"network" cty:"network" hcl:"network"`
	InstanceConfig       *common.FlatInstanceConfig       `mapstructure:"instance" cty:"instance" hcl:"instance"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":          &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":        &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":        &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":               &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":               &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":            &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":      &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"parent_id":                  &hcldec.AttrSpec{Name: "parent_id", Type: cty.String, Required: false},
		"service_account":            &hcldec.BlockSpec{TypeName: "service_account", Nested: hcldec.ObjectSpec((*common.FlatServiceAccountConfig)(nil).HCL2Spec())},
		"disk":                       &hcldec.BlockSpec{TypeName: "disk", Nested: hcldec.ObjectSpec((*common.FlatDiskConfig)(nil).HCL2Spec())},
		"base_image":                 &hcldec.BlockSpec{TypeName: "base_image", Nested: hcldec.ObjectSpec((*common.FlatBaseImageConfig)(nil).HCL2Spec())},
		"network":                    &hcldec.BlockSpec{TypeName: "network", Nested: hcldec.ObjectSpec((*common.FlatNetworkConfig)(nil).HCL2Spec())},
		"instance":                   &hcldec.BlockSpec{TypeName: "instance", Nested: hcldec.ObjectSpec((*common.FlatInstanceConfig)(nil).HCL2Spec())},
	}
	return s
}
