// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatBaseImageConfig is an auto-generated flat version of BaseImageConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBaseImageConfig struct {
	ID       *string `mapstructure:"id" cty:"id" hcl:"id"`
	ParentID *string `mapstructure:"parent_id" cty:"parent_id" hcl:"parent_id"`
	Family   *string `mapstructure:"family" cty:"family" hcl:"family"`
}

// FlatMapstructure returns a new FlatBaseImageConfig.
// FlatBaseImageConfig is an auto-generated flat version of BaseImageConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BaseImageConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatBaseImageConfig)
}

// HCL2Spec returns the hcl spec of a BaseImageConfig.
// This spec is used by HCL to read the fields of BaseImageConfig.
// The decoded values from this spec will then be applied to a FlatBaseImageConfig.
func (*FlatBaseImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"id":        &hcldec.AttrSpec{Name: "id", Type: cty.String, Required: false},
		"parent_id": &hcldec.AttrSpec{Name: "parent_id", Type: cty.String, Required: false},
		"family":    &hcldec.AttrSpec{Name: "family", Type: cty.String, Required: false},
	}
	return s
}

// FlatDiskConfig is an auto-generated flat version of DiskConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatDiskConfig struct {
	Type          *string `mapstructure:"type" cty:"type" hcl:"type"`
	SizeGibibytes *int64  `mapstructure:"size_gibibytes" cty:"size_gibibytes" hcl:"size_gibibytes"`
}

// FlatMapstructure returns a new FlatDiskConfig.
// FlatDiskConfig is an auto-generated flat version of DiskConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*DiskConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatDiskConfig)
}

// HCL2Spec returns the hcl spec of a DiskConfig.
// This spec is used by HCL to read the fields of DiskConfig.
// The decoded values from this spec will then be applied to a FlatDiskConfig.
func (*FlatDiskConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"type":           &hcldec.AttrSpec{Name: "type", Type: cty.String, Required: false},
		"size_gibibytes": &hcldec.AttrSpec{Name: "size_gibibytes", Type: cty.Number, Required: false},
	}
	return s
}

// FlatImageConfig is an auto-generated flat version of ImageConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatImageConfig struct {
	Name                     *string           `mapstructure:"name" cty:"name" hcl:"name"`
	Labels                   map[string]string `mapstructure:"labels" cty:"labels" hcl:"labels"`
	ImageFamily              *string           `mapstructure:"image_family" cty:"image_family" hcl:"image_family"`
	ImageFamilyHumanReadable *string           `mapstructure:"image_family_human_readable" cty:"image_family_human_readable" hcl:"image_family_human_readable"`
	Version                  *string           `mapstructure:"version" cty:"version" hcl:"version"`
	CPUArchitecture          *string           `mapstructure:"cpu_architecture" cty:"cpu_architecture" hcl:"cpu_architecture"`
	ParentID                 *string           `mapstructure:"parent_id" cty:"parent_id" hcl:"parent_id"`
	UnsupportedPlatforms     map[string]string `mapstructure:"unsupported_platforms" cty:"unsupported_platforms" hcl:"unsupported_platforms"`
	RecommendedPlatforms     []string          `mapstructure:"recommended_platforms" cty:"recommended_platforms" hcl:"recommended_platforms"`
}

// FlatMapstructure returns a new FlatImageConfig.
// FlatImageConfig is an auto-generated flat version of ImageConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ImageConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatImageConfig)
}

// HCL2Spec returns the hcl spec of a ImageConfig.
// This spec is used by HCL to read the fields of ImageConfig.
// The decoded values from this spec will then be applied to a FlatImageConfig.
func (*FlatImageConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":                        &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"labels":                      &hcldec.AttrSpec{Name: "labels", Type: cty.Map(cty.String), Required: false},
		"image_family":                &hcldec.AttrSpec{Name: "image_family", Type: cty.String, Required: false},
		"image_family_human_readable": &hcldec.AttrSpec{Name: "image_family_human_readable", Type: cty.String, Required: false},
		"version":                     &hcldec.AttrSpec{Name: "version", Type: cty.String, Required: false},
		"cpu_architecture":            &hcldec.AttrSpec{Name: "cpu_architecture", Type: cty.String, Required: false},
		"parent_id":                   &hcldec.AttrSpec{Name: "parent_id", Type: cty.String, Required: false},
		"unsupported_platforms":       &hcldec.AttrSpec{Name: "unsupported_platforms", Type: cty.Map(cty.String), Required: false},
		"recommended_platforms":       &hcldec.AttrSpec{Name: "recommended_platforms", Type: cty.List(cty.String), Required: false},
	}
	return s
}

// FlatInstanceConfig is an auto-generated flat version of InstanceConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatInstanceConfig struct {
	Platform *string `mapstructure:"platform" cty:"platform" hcl:"platform"`
	Preset   *string `mapstructure:"preset" cty:"preset" hcl:"preset"`
}

// FlatMapstructure returns a new FlatInstanceConfig.
// FlatInstanceConfig is an auto-generated flat version of InstanceConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*InstanceConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatInstanceConfig)
}

// HCL2Spec returns the hcl spec of a InstanceConfig.
// This spec is used by HCL to read the fields of InstanceConfig.
// The decoded values from this spec will then be applied to a FlatInstanceConfig.
func (*FlatInstanceConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"platform": &hcldec.AttrSpec{Name: "platform", Type: cty.String, Required: false},
		"preset":   &hcldec.AttrSpec{Name: "preset", Type: cty.String, Required: false},
	}
	return s
}

// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkConfig struct {
	SubnetID                 *string `mapstructure:"subnet_id" cty:"subnet_id" hcl:"subnet_id"`
	AssociatePublicIpAddress *bool   `mapstructure:"associate_public_ip_address" cty:"associate_public_ip_address" hcl:"associate_public_ip_address"`
	PublicAllocationID       *string `mapstructure:"public_allocation_id" cty:"public_allocation_id" hcl:"public_allocation_id"`
}

// FlatMapstructure returns a new FlatNetworkConfig.
// FlatNetworkConfig is an auto-generated flat version of NetworkConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkConfig)
}

// HCL2Spec returns the hcl spec of a NetworkConfig.
// This spec is used by HCL to read the fields of NetworkConfig.
// The decoded values from this spec will then be applied to a FlatNetworkConfig.
func (*FlatNetworkConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"subnet_id":                   &hcldec.AttrSpec{Name: "subnet_id", Type: cty.String, Required: false},
		"associate_public_ip_address": &hcldec.AttrSpec{Name: "associate_public_ip_address", Type: cty.Bool, Required: false},
		"public_allocation_id":        &hcldec.AttrSpec{Name: "public_allocation_id", Type: cty.String, Required: false},
	}
	return s
}

// FlatServiceAccountConfig is an auto-generated flat version of ServiceAccountConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatServiceAccountConfig struct {
	PrivateKeyFile *string `mapstructure:"private_key_file" cty:"private_key_file" hcl:"private_key_file"`
	PrivateKey     *string `mapstructure:"private_key" cty:"private_key" hcl:"private_key"`
	PublicKeyID    *string `mapstructure:"public_key_id" cty:"public_key_id" hcl:"public_key_id"`
	AccountID      *string `mapstructure:"account_id" cty:"account_id" hcl:"account_id"`
}

// FlatMapstructure returns a new FlatServiceAccountConfig.
// FlatServiceAccountConfig is an auto-generated flat version of ServiceAccountConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ServiceAccountConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatServiceAccountConfig)
}

// HCL2Spec returns the hcl spec of a ServiceAccountConfig.
// This spec is used by HCL to read the fields of ServiceAccountConfig.
// The decoded values from this spec will then be applied to a FlatServiceAccountConfig.
func (*FlatServiceAccountConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"private_key_file": &hcldec.AttrSpec{Name: "private_key_file", Type: cty.String, Required: false},
		"private_key":      &hcldec.AttrSpec{Name: "private_key", Type: cty.String, Required: false},
		"public_key_id":    &hcldec.AttrSpec{Name: "public_key_id", Type: cty.String, Required: false},
		"account_id":       &hcldec.AttrSpec{Name: "account_id", Type: cty.String, Required: false},
	}
	return s
}
