// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatServiceAccountConfig is an auto-generated flat version of ServiceAccountConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatServiceAccountConfig struct {
	PrivateKeyFileEnv *string `mapstructure:"private_key_file_env" required:"true" cty:"private_key_file_env" hcl:"private_key_file_env"`
	PublicKeyIDEnv    *string `mapstructure:"public_key_id_env" required:"true" cty:"public_key_id_env" hcl:"public_key_id_env"`
	AccountIDEnv      *string `mapstructure:"account_id_env" required:"true" cty:"account_id_env" hcl:"account_id_env"`
}

// FlatMapstructure returns a new FlatServiceAccountConfig.
// FlatServiceAccountConfig is an auto-generated flat version of ServiceAccountConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*ServiceAccountConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatServiceAccountConfig)
}

// HCL2Spec returns the hcl spec of a ServiceAccountConfig.
// This spec is used by HCL to read the fields of ServiceAccountConfig.
// The decoded values from this spec will then be applied to a FlatServiceAccountConfig.
func (*FlatServiceAccountConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"private_key_file_env": &hcldec.AttrSpec{Name: "private_key_file_env", Type: cty.String, Required: false},
		"public_key_id_env":    &hcldec.AttrSpec{Name: "public_key_id_env", Type: cty.String, Required: false},
		"account_id_env":       &hcldec.AttrSpec{Name: "account_id_env", Type: cty.String, Required: false},
	}
	return s
}
